name: Reusable Build

on:
  workflow_call:
    inputs:
      enable_deploy:
        required: false
        type: boolean
        default: false
      verbose:
        required: false
        type: string
        default: "false"

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  emulation-root:
    name: Windows 2025 Emulation Root
    runs-on: windows-2025
    steps:
      - name: Checkout Source
        uses: actions/checkout@v7

      - name: Download DirectX Runtime
        run: curl --connect-timeout 20 --max-time 200 --retry 5 --retry-delay 2 --retry-max-time 200 -L -o directx_Jun2010_redist.exe https://download.microsoft.com/download/8/4/A/84A35BF1-DAFE-4AE8-82AF-AD2AE20B6B14/directx_Jun2010_redist.exe

      - name: Extract DirectX Runtime
        run: 'cmd /c "start /wait directx_Jun2010_redist.exe /Q /T:${{ github.workspace }}/dxrt"'

      - name: Install DirectX Runtime
        run: 'cmd /c "start /wait .\dxrt\dxsetup.exe /silent"'

      - name: Create emulation root
        run: src/tools/create-root.bat

      - name: Upload Windows 2025 emulation root
        uses: pyTooling/upload-artifact@v7
        with:
          name: Windows 2025 Emulation Root
          working-directory: root
          path: "*"
          retention-days: 1
